apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-sample
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: openshift-helm
    repoURL: 'https://github.com/rutvik-nvs/Quarkus-ACS-Tekton.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: sandbox