kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: java-sample
  namespace: {{ .Values.namespace }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.source_url }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.jvm
  output:
    to:
      kind: DockerImage
      name: >-
        {{ .Values.image_url }}:{{ .Values.image_version }}
    pushSecret:
      name: github-package