name: Tekton Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  trigger-tekton-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Openshift CLI
      uses: redhat-actions/oc-installer@v1

    - name: Login to Openshift
      run: oc login ${{ secrets.OCP_API_URL }} -u ${{ secrets.OCP_API_URL }} -p ${{ secrets.OCP_API_URL }}

    - name: Create roxsecrets
      run: oc create secret generic roxsecrets -n sandbox --dry-run=client -o yaml --from-literal=rox_api_token=${{ secrets.RHACS_API_TOKEN }} --from-literal=rox_central_endpoint=${{ secrets.RHACS_API_URL }} | oc apply -f -

    - name: Trigger Tekton Pipeline
      run: |
          curl --insecure -X POST -H "Content-Type: application/json" -d '{"key": "value"}' ${{ secrets.OCP_TEKTON_WEBHOOK_URL }}

    - name: Delete roxsecrets
      run: oc delete secret roxsecrets -n sandbox

    - name: Logout from Openshift
      run: oc logout
