name: Tekton Build

# Controls when the action will run. Workflow runs when manually triggered using the UI or API
on:
  workflow_dispatch:

jobs:
  trigger-tekton-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Openshift CLI
      uses: redhat-actions/oc-installer@v1

    - name: Install Tekton CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/0.19.1/tkn-linux-amd64-0.19.1.tar.gz
        tar xvzf tkn-linux-amd64-0.19.1.tar.gz -C /usr/local/bin tkn

    - name: Login to Openshift
      run: oc login ${{ secrets.OCP_API_URL }} -u ${{ secrets.OCP_API_USERNAME }} -p ${{ secrets.OCP_API_PASSWORD }} --insecure-skip-tls-verify

    - name: Create roxsecrets
      run: oc create secret generic roxsecrets -n sandbox --dry-run=client -o yaml --from-literal=rox_api_token=${{ secrets.RHACS_API_TOKEN }} --from-literal=rox_central_endpoint=${{ secrets.RHACS_API_URL }} | oc apply -f -

    - name: Trigger Tekton Pipeline
      run: |
          tkn start pipeline s2i-build-scan-deploy -w name=workspace,claimName=tekton-workspace -n sandbox --showlog

    # - name: Trigger Tekton Pipeline
    #   run: |
    #       curl --insecure -X POST -H "Content-Type: application/json" -d '{"key": "value"}' ${{ secrets.OCP_TEKTON_WEBHOOK_URL }}

    - name: Logout from Openshift
      run: oc logout
